const worksDesc = [
  "Luigi Zuccheri, Untitled (Paesaggio con mela a figure unmane), 1950/55. tempera on board, 15x20 cm.",
  "Luigi Zuccheri, Untitled (Balena e villaggio), 1950/55, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Topo, due mele e un frate), 1945/50, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Granchio, pescatore e cicogna), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Figura umana e calabrone), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con topo e figure umane),1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con formicaio e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con rana e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Cavalletta e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Chiocciola, calabrone e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio nebbioso con grillo, calabrone e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Corvo e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Frate, farfalla e cervo volante), 1950/55, tempera on board, 25x30 cm.",
  "Luigi Zuccheri, Untitled (Lucertola e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Rana e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Stagno con rane), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Rana, dalia gigante, calabrone e figura umana), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Faina), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Frate con vespe, scorpioni, coleotteri e lupo), 1950/55, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Insetti e figure umane), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con beccaccia, chiocciola, ragno e figura umana), 1955/60, tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Notturno con insetti e figura umana), 1950/55, tempera on board, 25x30 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con insetti e figure umane), 1955/60, tempera on board, 20x25 cm.",
  "Luigi Zuccheri, Untitled (Faina e chiocciola), 1955/1960, tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Stagno con pesci e figura umana), 1950/55, tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Donnola e figure umane), 1955/60, tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con serpente, mele, falco e figura umana), 1950/55, tempera on board, 25x30 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con erbe spontanee, insetti e figure umane), 1955/60 tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Piazza con zucca, topo, falco e figure umane), 1955/60, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Piazza con zucca, lucertole, insetti e figure umane), 1955/60, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con tartarughe), 1950/1955, tempera on board, 40x50 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con erbe spontanee e zucca), 1955/60 tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Albero morto, figure umane e api), 1950/55, tempera on canvas, 25x35 cm.",
  "Luigi Zuccheri, Untitled (Erbe spontanee, insetti e figure umane), 1950/55, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Temporale con insetti e figure umane), 1950/55, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Collina con uccelli), 1945/50, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con cavallette e figura umana),  1950/55, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con cetonie, angelo e figura umana), 1945/50, tempera on canvas, 30x40 cm.",
  "Luigi Zuccheri, Untitled (Villaggio con pere e passero), 1945/50, tempera on canvas, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con pere, insetti e figura umana), 1945/50, tempera on canvas, 35x50 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con ape e vespa), 1945/50, tempera on board, 30x25 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con insetti e figura umana), 1945/50, tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Notturno con falene, grilli e figure umane), 1950/55, tempera on board, 30x35 cm.",
  "Luigi Zuccheri, Untitled (Villaggio con donnola e figura umana), 1955/60, tempera on board, 30x40 cm.",
  "Luigi Zuccheri, Untitled (Riccio e figura umana), 1955/60, tempera on canvas, 32x35 cm.",
  "Luigi Zuccheri, Untitled (Tarassaco, insetti e frate), 1955/60, tempera on board, 30x40 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con faina e albero), 1955/60, tempera on board, 45x40 cm.",
  "Luigi Zuccheri, Untitled (Delfino con bragozzo), 1950/55, tempera on board, 40x50 cm.",
  "Luigi Zuccheri, Untitled (Aia con anatra, coniglio e figure umane), 1955/60, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Coniglio, figura umana e gazza), 1955/60, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Marina con sgombro e conchiglie), 1945/50, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Bagnante con pesce e uccelli marini), 1950/55, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Palude con rana e figura umana), 1950/55, tempera on board, 40x45 cm.",
  "Luigi Zuccheri, Untitled (Paesaggio con sparviero e lepri), 1955/60, tempera on board, 60x50 cm.",
  "Luigi Zuccheri, Untitled (Cespuglio con faina, calabrone e frate), 1950/55, tempera on board, 40x45 cm",
];

export default worksDesc;
